"""create team_node table

Revision ID: 3303734b29d2
Revises: 
Create Date: 2025-11-26 16:00:10.452245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3303734b29d2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_node',
    sa.Column('node_id', sa.UUID(), nullable=False),
    sa.Column('founding_year', sa.Integer(), nullable=False),
    sa.Column('dissolution_year', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('founding_year >= 1900', name='check_founding_year_minimum'),
    sa.PrimaryKeyConstraint('node_id')
    )
    
    # Create indexes for better query performance
    op.create_index('idx_team_node_founding', 'team_node', ['founding_year'])
    op.create_index('idx_team_node_dissolution', 'team_node', ['dissolution_year'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop indexes before dropping table
    op.drop_index('idx_team_node_dissolution', table_name='team_node')
    op.drop_index('idx_team_node_founding', table_name='team_node')
    op.drop_table('team_node')
    # ### end Alembic commands ###
